config/routes.rb
Rails.application.routes.draw do

	resources :resume_entries
	resources :timesheets

	devise_for :users, :controllers => { registrations: 'registrations' }

	devise_scope :user do
		get 'login', to: 'devise/sessions#new'
	end

	resources :tools do
		member do
			get "getToolInfo"
			post "deleteTool"
			post "addEditTool"
			post "updateFeaturedTool"
		end
	end

	resources :projects do
		member do
			get "getProjectInfo"
			get "checkAppStatus"
			post "deleteProject"
			post "addEditProject"
			post "updateFeaturedProject"
		end
	end

	get 'resume', to: 'resumes#index', as: :resume
	resources :resumes

	get 'about', to: 'about#index', as: :about
	get 'about/index'

	root to: 'welcome#index'
	get 'welcome/index'


	# this is the catch-all route for pages that people might reach in error,
	# and will redirect them back to the index page.
	#match '*', via: :all, to: 'welcome#index'
	match "*path", to: redirect('/'), via: :all

end

app/models/tool.rb
class Tool < ActiveRecord::Base

	def self.get_featured
		Tool.where(featured: true)
	end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
	before_action :set_tool, only: [:show, :edit, :update, :destroy]

	# GET /tools
	# GET /tools.json
	def index
		@tools = Tool.all
	end

	# GET /tools/1
	# GET /tools/1.json
	def show
	end

	# GET /tools/new
	def new
		@tool = Tool.new
	end

	# GET /tools/1/edit
	def edit
	end


	# POST /tools/1/addEditTool
	def addEditTool
		tid = params[:item_id]

		response = {}
		content  = {}
		status   = ""
		message  = ""

		begin
			new_or_edit = "new"
			update_success = false
			tool_params = { :name => params['name'], :link => params['link'], :description => params['description']}
			if tid.to_i == 0 # new tool
				@tool = Tool.new(tool_params)
				update_success = @tool.save
			else
				new_or_edit = "edit"
				@tool = Tool.find(tid.to_i)
				update_success = @tool.update(tool_params)
			end

			status = update_success ? "success" : "failure"
			message = update_success ? "Tool updated successfully!" : "Error during tool update"
			content['project'] = @tool.attributes
			content['type'] = "tool"
			content['new_or_edit'] = new_or_edit

			response['status'] = "success"
			response['message'] = "Returning data for #{@tool.name}"
			response['content'] = content
		rescue => error
			response['status'] = "failure"
			response['message'] = "Error: #{error.message}"
			response['content'] = error.backtrace
		ensure
			respond_to do |format|
				format.html { render :json => response.to_json }
			end
		end
	end


	def getToolInfo
		pid = params[:item_id]

		response = {}
		content  = {}
		status   = ""
		message  = ""

		begin
			@tool = Tool.find(pid.to_i)
			tool = @tool.attributes
			content['type'] = "tool"
			content['project'] = tool

			response['status'] = "success"
			response['message'] = "Returning data for tool #{@tool.name}"
			response['content'] = content
		rescue => error
			response['status'] = "failure"
			response['message'] = "Error: #{error.message}"
			response['content'] = error.backtrace
		ensure
			respond_to do |format|
				format.html { render :json => response.to_json }
			end
		end
	end


	def deleteTool
		pid = params[:item_id]

		response = {}
		content  = {}
		status   = ""
		message  = ""

		begin
			@tool = Tool.find(pid.to_i)
			tool = @tool.attributes
			content['type'] = "tool"
			content['project'] = tool
			@tool.destroy

			content['num_featured'] = Project.get_featured.size + Tool.get_featured.size

			response['status'] = "success"
			response['message'] = "Successfully deleted tool #{tool['name']}"
			response['content'] = content
		rescue => error
			response['status'] = "failure"
			response['message'] = "Error: #{error.message}"
			response['content'] = error.backtrace
		ensure
			respond_to do |format|
				format.html { render :json => response.to_json }
			end
		end
	end


	def updateFeaturedTool
		tid = params[:item_id]

		response = {}
		content  = {}
		status   = ""
		message  = ""

		begin
			tool_params = { :featured => params[:featured] }
			@tool = Tool.find(tid.to_i)
			@tool.update(tool_params)
			content['type'] = "tool"
			content['project'] = @tool.attributes

			response['status']  = "success"
			response['message'] = "Successfully updated tool #{@tool.name}"
			response['content'] = content
		rescue => error
			response['status'] = "failure"
			response['message'] = "Error: #{error.message}"
			response['content'] = error.backtrace
		ensure
			respond_to do |format|
				format.html { render :json => response.to_json }
			end
		end
	end


	# POST /tools
	# POST /tools.json
	def create
		@tool = Tool.new(tool_params)

		respond_to do |format|
			if @tool.save
				format.html { redirect_to tools_url, notice: 'Tool was successfully created.' }
				format.json { render :show, status: :created, location: @tool }
			else
				format.html { render :new }
				format.json { render json: @tool.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /tools/1
	# PATCH/PUT /tools/1.json
	def update
		respond_to do |format|
			if @tool.update(tool_params)
				format.html { redirect_to tools_url, notice: 'Tool was successfully updated.' }
				format.json { render :show, status: :ok, location: @tool }
			else
				format.html { render :edit }
				format.json { render json: @tool.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /tools/1
	# DELETE /tools/1.json
	def destroy
		@tool.destroy
		respond_to do |format|
			format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tool_params
      params.require(:tool).permit(:name, :link, :description)
    end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_form.html.erb
<%= form_for(@tool, html: { class: "rails_form", style: 'height:400px;' }) do |f| %>
	<% if @tool.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@tool.errors.count, "error") %> prohibited this tool from being saved:</h2>
			<ul>
			<% @tool.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field w100fl">
		<%= f.label :name %><br>
		<%= f.text_field :name, { class: "txt100", style: "" } %>
	</div>
	<div class="field w100fl">
		<%= f.label :link %><br>
		<%= f.text_field :link, { class: "txt100", style: "" } %>
	</div>
	<div class="field w100fl">
		<%= f.label :description %><br>
		<%= f.text_area :description, { class: "txt100", style: "height:150px" } %>
	</div>
	<div class="actions w100fl">
		<%= f.submit "Submit", { class: "btn btn-success", style: "float:left;width:150px;", onclick: "return checkToolForm();" } %>
		<%= link_to 'Back', projects_path, { class: "btn btn-primary", style: "float:right;width:150px;" } %>
	</div>
<% end %>

app/views/tools/edit.html.erb
<% content_for :main do %>
<h3>Editing Tool: <%= @tool.name.html_safe %></h3>

<%= render 'form' %>

<% end %>

app/views/tools/index.html.erb
<% content_for :main do %>
<p id="notice" style="display:none;"><%= notice %></p>

<h3>
	Please select a Tool:
	<% if user_signed_in? %>
		<%= link_to 'New Tool', new_tool_path, { class: "btn btn-default btn-xs", style: "float:right;margin-top:2px;padding-left:10px;padding-right:10px;" } %>
	<% end %>
</h3>

<table class="table">
	<thead>
		<tr>
			<th style="width:30px;"></th>
			<th style="width:200px;">Name</th>
			<th>Description</th>
			<th style="width:30px;"></th>
		</tr>
	</thead>

	<tbody>
		<% @tools.each do |tool| %>
			<tr>
				<td class="vam"><a style="color:#204d74;" title="Edit <%= tool.name %>" href="<%= edit_tool_path(tool) %>"><i class="glyphicon glyphicon-edit"></i></a></td>
				<td class="vam"><%= link_to tool.name, tool.link, target: "_blank" %></td>
				<td class="vam"><%= tool.description %></td>
				<td class="vam">
					<%= link_to tool, method: :delete, data: { confirm: 'Are you sure you want to delete this tool?' }, style: "color:#C9302C;" do %>
						<i class="glyphicon glyphicon-trash"></i>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<% end %>

app/views/tools/new.html.erb
<% content_for :main do %>
<h3>New Tool</h3>

<%= render 'form' %>

<% end %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tool.name %>
</p>

<p>
  <strong>Link:</strong>
  <%= @tool.link %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tool.description %>
</p>

<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>