config/routes.rb
Rails.application.routes.draw do

	resources :resume_entries
	resources :timesheets

	devise_for :users, :controllers => { registrations: 'registrations' }

	devise_scope :user do
		get 'login', to: 'devise/sessions#new'
	end

	resources :tools do
		member do
			get "getToolInfo"
			post "deleteTool"
			post "addEditTool"
			post "updateFeaturedTool"
		end
	end

	resources :projects do
		member do
			get "getProjectInfo"
			get "checkAppStatus"
			post "deleteProject"
			post "addEditProject"
			post "updateFeaturedProject"
		end
	end

	get 'resume', to: 'resumes#index', as: :resume
	resources :resumes

	get 'about', to: 'about#index', as: :about
	get 'about/index'

	root to: 'welcome#index'
	get 'welcome/index'


	# this is the catch-all route for pages that people might reach in error,
	# and will redirect them back to the index page.
	#match '*', via: :all, to: 'welcome#index'
	match "*path", to: redirect('/'), via: :all

end

app/models/resume_entry.rb
class ResumeEntry < ActiveRecord::Base

	belongs_to :resume

	def date_difference
		sd = self.start_date
		ed = self.is_current? ? Time.now : self.end_date
		months = (ed.year * 12 + ed.month) - (sd.year * 12 + sd.month)
		months.divmod(12)
	end

end

app/controllers/resume_entries_controller.rb
class ResumeEntriesController < ApplicationController
	before_action :set_resume_entry, only: [:show, :edit, :update, :destroy]

	# GET /resume_entries
	# GET /resume_entries.json
	def index
		@resume_entries = ResumeEntry.all.order("start_date DESC")
	end

	# GET /resume_entries/1
	# GET /resume_entries/1.json
	def show
	end

	# GET /resume_entries/new
	def new
		@resume_entry = ResumeEntry.new
	end

	# GET /resume_entries/1/edit
	def edit
	end

	# POST /resume_entries
	# POST /resume_entries.json
	def create
		@resume_entry = ResumeEntry.new(resume_entry_params)
		#	logger.debug "\n\n\n\n\n\n\nRESUME ENTRY START IS: #{@resume_entry.start_date}\n\n\n\n\n\n\n"

		if resume_entry_params[:is_current].to_i.equal? 1
			ResumeEntry.all.update_all(is_current: false)
		end

		respond_to do |format|
			if @resume_entry.save
				format.html { redirect_to resumes_url, notice: 'Resume entry was successfully created.' }
				format.json { render :show, status: :created, location: @resume_entry }
			else
				format.html { render :new }
				format.json { render json: @resume_entry.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /resume_entries/1
	# PATCH/PUT /resume_entries/1.json
	def update

		if resume_entry_params[:is_current].to_i.equal? 1
			ResumeEntry.all.update_all(is_current: false)
		end

		respond_to do |format|
			if @resume_entry.update(resume_entry_params)
				format.html { redirect_to resumes_url, notice: 'Resume entry was successfully updated.' }
				format.json { render :show, status: :ok, location: @resume_entry }
			else
				format.html { render :edit }
				format.json { render json: @resume_entry.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /resume_entries/1
	# DELETE /resume_entries/1.json
	def destroy
		@resume_entry.destroy
		respond_to do |format|
			format.html { redirect_to resume_entries_url, notice: 'Resume entry was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume_entry
      @resume_entry = ResumeEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_entry_params
      params.require(:resume_entry).permit(:position, :company, :company_url, :description, :start_date, :end_date, :is_current)
    end
end

app/helpers/resume_entries_helper.rb
module ResumeEntriesHelper
end

app/views/resume_entries/_form.html.erb
<%= tinymce_assets %>
<%= form_for(@resume_entry, html: { class: "rails_form", style: 'height:800px;' }) do |f| %>

	<% if @resume_entry.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@resume_entry.errors.count, "error") %> prohibited this resume_entry from being saved:</h2>
			<ul>
			<% @resume_entry.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field w100fl">
		<%= f.label :position %><br>
		<%= f.text_field :position, { class: "txt100", style: "" } %>
	</div>
	<div class="field w100fl">
		<%= f.label :company %><br>
		<%= f.text_field :company, { class: "txt100", style: "" } %>
	</div>
	<div class="field w100fl">
		<%= f.label :company_url %><br>
		<%= f.text_field :company_url, { class: "txt100", style: "" } %>
	</div>
	<div class="field w100fl">
		<%= f.label :is_current, "Current Position?", { style: "float:left;" } %><%= f.check_box :is_current, { style: "float:left;margin-top:5px;margin-left:10px;" } %>
	</div>
	<div class="field w50fl">
		<%= f.label :start_date %><br>
		<%= f.date_select :start_date, { :order => [:month, :year], :start_year => 1990, :discard_day => true }, { class: "", style: "width:40%;margin-right:10px;float:left;" } %>
	</div>
	<div class="field w50fl">
		<%= f.label :end_date %><br>
		<%= f.date_select :end_date, { :order => [:month, :year], :start_year => 1990, :discard_day => true }, { class: "", style: "width:40%;margin-right:10px;float:left;" } %>
	</div>
	<div class="field w100fl">
		<%= f.label :description %><br>
		<%= f.text_area :description, { class: "tinymce", style: "height:150px" } %>
		<%= tinymce %>
	</div>
	<div class="actions w100fl">
		<%= f.submit "Submit", { class: "btn btn-success", style: "float:left;width:150px;", onclick: "return checkResumeEntryForm();" } %>
		<%= link_to 'Back', resume_path, { class: "btn btn-primary", style: "float:right;width:150px;" } %>
	</div>

<% end %>

app/views/resume_entries/edit.html.erb
<% content_for :main do %>
	<h3>Editing Resume Entry</h3>
	<%= render 'form' %>
<% end %>

app/views/resume_entries/index.html.erb
<% content_for :main do %>

<h3>Resume Entries</h3>

<table class="table">
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
<!--      <th style="width:400px">Description</th>//-->
      <th>Start date</th>
      <th>End date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @resume_entries.each do |resume_entry| %>
      <tr>
        <td><%= resume_entry.position %></td>
        <td><a href="resume_entry.company_url" target="_blank"><%= resume_entry.company %></a></td>
<!--    <td><%# begin %><%#= resume_entry.description.html_safe %><%# rescue;end %></td>//-->
        <td><%= resume_entry.start_date.strftime("%b, %Y") %></td>
        <td><%= resume_entry.end_date.strftime("%b, %Y") %></td>
        <td><%= link_to 'Edit', edit_resume_entry_path(resume_entry) %></td>
        <td><%= link_to 'Destroy', resume_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume entry', new_resume_entry_path, { class: "btn btn-primary", style: "float:left;width:150px;" } %>
<% end %>

app/views/resume_entries/new.html.erb
<% content_for :main do %>
	<h3>New Resume Entry</h3>
	<%= render 'form' %>
<% end %>

app/views/resume_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @resume_entry.position %>
</p>

<p>
  <strong>Company:</strong>
  <%= @resume_entry.company %>
</p>

<p>
  <strong>Company url:</strong>
  <%= @resume_entry.company_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resume_entry.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @resume_entry.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @resume_entry.end_date %>
</p>

<%= link_to 'Edit', edit_resume_entry_path(@resume_entry) %> |
<%= link_to 'Back', resume_entries_path %>