config/routes.rb
Rails.application.routes.draw do

	resources :resume_entries
	resources :timesheets

	devise_for :users, :controllers => { registrations: 'registrations' }

	devise_scope :user do
		get 'login', to: 'devise/sessions#new'
	end

	resources :tools do
		member do
			get "getToolInfo"
			post "deleteTool"
			post "addEditTool"
			post "updateFeaturedTool"
		end
	end

	resources :projects do
		member do
			get "getProjectInfo"
			get "checkAppStatus"
			post "deleteProject"
			post "addEditProject"
			post "updateFeaturedProject"
		end
	end

	get 'resume', to: 'resumes#index', as: :resume
	resources :resumes

	get 'about', to: 'about#index', as: :about
	get 'about/index'

	root to: 'welcome#index'
	get 'welcome/index'


	# this is the catch-all route for pages that people might reach in error,
	# and will redirect them back to the index page.
	#match '*', via: :all, to: 'welcome#index'
	match "*path", to: redirect('/'), via: :all

end

app/views/shared/_foot.html.erb
<footer class="footer">
	<div class="container">
		<p class="text-muted foot-p">
			Built by <a href="https://twitter.com/sixfivebeastman" title="Email Tim Andrews" target="_blank">Tim Andrews</a> in <%= "#{Time.new.year}" %>.
		</p>
		<p class="text-muted foot-p" style="float:right;">
			<a href="https://github.com/musicmunky" title="Tim Andrews on GitHub" target="_blank">
              <%= image_tag("octocat.png", {alt: "GitHub Octocat", style:"width:40px;"}) %>
            </a>
		</p>
	</div>
</footer>

app/views/shared/_head.html.erb
<head>
	<%= favicon_link_tag %>
	<title><%= "#{Rails.application.config.app_name}" %><%= content_for?(:title) ?  " | #{content_for(:title)}" : "" %></title>
	<%= stylesheet_link_tag "application", media: "all" %>
	<%#= stylesheet_link_tag params[:controller] %>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster" />
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Cutive+Mono" />
	<%= javascript_include_tag "application" %>
	<%#= javascript_include_tag params[:controller] %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

app/views/shared/_lorem.html.erb
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>

app/views/shared/_nav.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "TWA", root_path(), { class: "navbar-brand" } %>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="<%= is_active('about') %>"><%= link_to "About", about_path %></li>
				<li class="<%= is_active('projects') %>"><%= link_to("Projects", projects_path) %></li>
				<li class="<%= is_active('resumes') %>"><%= link_to("Resume", resume_path) %></li>
				<% host = request.host_with_port %>
				<% featured = Project.get_featured + Tool.get_featured %>
				<% featured.each do |item| %>
					<% url_array  = /(\w+(\.+\w+)+)/.match(item.link) %>
					<% url_params = (!url_array.nil? and url_array.size > 0 and url_array[0] == host) ? {} : { target: "_blank" } %>
					<li class="<%= is_active(item.name.downcase) %>"><%= link_to item.name, item.link, url_params %></li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li>
						<%= link_to(current_user.get_name, edit_user_registration_path, { class: "navlink", style: "text-decoration:none;color:#9D9D9D" }) %> |
						<%= link_to('Logout', destroy_user_session_path, { :method => :delete, style: "text-decoration:none;color:#9D9D9D" }) %>
					</li>
				<!--<li><%#= link_to('Login', new_user_session_path, { class: "btn btn-primary navbar-btn", style:"text-decoration:none;color:#FFF;padding-top:5px;padding-bottom:5px;" })  %>
					</li>//-->
				<% end %>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</div>

app/views/shared/_short_lorem.html.erb
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>