config/routes.rb
Rails.application.routes.draw do

	resources :resume_entries
	resources :timesheets

	devise_for :users, :controllers => { registrations: 'registrations' }

	devise_scope :user do
		get 'login', to: 'devise/sessions#new'
	end

	resources :tools do
		member do
			get "getToolInfo"
			post "deleteTool"
			post "addEditTool"
			post "updateFeaturedTool"
		end
	end

	resources :projects do
		member do
			get "getProjectInfo"
			get "checkAppStatus"
			post "deleteProject"
			post "addEditProject"
			post "updateFeaturedProject"
		end
	end

	get 'resume', to: 'resumes#index', as: :resume
	resources :resumes

	get 'about', to: 'about#index', as: :about
	get 'about/index'

	root to: 'welcome#index'
	get 'welcome/index'


	# this is the catch-all route for pages that people might reach in error,
	# and will redirect them back to the index page.
	#match '*', via: :all, to: 'welcome#index'
	match "*path", to: redirect('/'), via: :all

end

app/models/resume.rb
class Resume < ActiveRecord::Base

	belongs_to :user
	has_many :resume_entries

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
	before_action :set_resume, only: [:show, :edit, :update, :destroy]

	def index
		@resume = {}
		if params[:id].nil? or params[:id].is_blank?
			@resume = User.find(1).resumes.first
		else
			@resume = Resume.find(params[:id])
		end
		@resume_entries = @resume.resume_entries.order("start_date DESC, end_date DESC")
	end

	# GET /resumes/1
	# GET /resumes/1.json
	def show
	end

	# GET /resumes/new
	def new
		@resume = Resume.new
	end

	# GET /resumes/1/edit
	def edit
	end

	# POST /resumes
	# POST /resumes.json
	def create
		@resume = Resume.new(resume_params)

		respond_to do |format|
			if @resume.save
				format.html { redirect_to resumes_url, notice: 'Resume entry was successfully created.' }
				format.json { render :show, status: :created, location: @resume }
			else
				format.html { render :new }
				format.json { render json: @resume.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /resumes/1
	# PATCH/PUT /resumes/1.json
	def update
		respond_to do |format|
			if @resume.update(resume_params)
				format.html { redirect_to resumes_url, notice: 'Resume was successfully updated.' }
				format.json { render :show, status: :ok, location: @resume }
			else
				format.html { render :edit }
				format.json { render json: @resume.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /resumes/1
	# DELETE /resumes/1.json
	def destroy
		@resume.destroy
		respond_to do |format|
			format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:summary, :education, :skills, :additional_info)
    end


end

app/views/resumes/_form.html.erb
<%= tinymce_assets %>
<%= form_for(@resume, html: { class: "rails_form", style: 'height:1550px;width:800px;' }) do |f| %>

	<% if @resume.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume_entry from being saved:</h2>
			<ul>
			<% @resume.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field w100fl" style="margin-bottom:50px;">
		<%= f.label :summary, { style:"font-size:18px" } %><br>
		<%= f.text_area :summary, { class: "tinymce", style: "height:150px" } %>
	</div>
	<div class="field w100fl" style="margin-bottom:50px;">
		<%= f.label :education, { style:"font-size:18px" } %><br>
		<%= f.text_area :education, { class: "tinymce", style: "height:150px" } %>
	</div>
	<div class="field w100fl" style="margin-bottom:50px;">
		<%= f.label :skills, { style:"font-size:18px" } %><br>
		<%= f.text_area :skills, { class: "tinymce", style: "height:150px" } %>
	</div>
	<div class="field w100fl" style="margin-bottom:50px;">
		<%= f.label :additional_info, { style:"font-size:18px" } %><br>
		<%= f.text_area :additional_info, { class: "tinymce", style: "height:150px" } %>
		<%= tinymce %>
	</div>
	<div class="actions w100fl">
		<%= f.submit "Submit", { class: "btn btn-success", style: "float:left;width:150px;", onclick: "return checkResumeForm();" } %>
		<%= link_to 'Back', resumes_path, { class: "btn btn-primary", style: "float:right;width:150px;" } %>
	</div>

<% end %>

app/views/resumes/edit.html.erb
<% content_for :main do %>
	<h3>Editing Resume</h3>
	<%= render 'form' %>
<% end %>

app/views/resumes/index.html.erb
<% content_for :main do %>
	<% fname = current_user.nil? ? "Tim" : current_user.first_name %>
	<h3 style="font-size:2.5em;"><%= fname %>'s Resume
		<% if user_signed_in? %>
			<%= link_to 'New Entry', new_resume_entry_path, { class: "btn btn-default btn-xs", style: "float:right;margin-top:2px;padding-left:10px;padding-right:10px;" } %>
		<% end %>
	</h3>

	<!-- Summary section //-->
	<span class="w100fl resume_heading">Summary</span>
	<div class="w100fl resume_entry">
		<%= @resume.summary.html_safe %>
	</div>

	<!-- Skills section //-->
	<span class="w100fl resume_heading">Skills Overview</span>
	<div class="w100fl resume_entry">
		<%= @resume.skills.html_safe %>
	</div>


	<!-- Education section //-->
	<span class="w100fl resume_heading">Education</span>
	<div class="w100fl resume_entry">
		<%= @resume.education.html_safe %>
	</div>

	<!-- Experience section //-->
	<span class="w100fl resume_heading">Previous Experience</span>
	<% @resume_entries.each do |resume_entry| %>
		<div class="w100fl resume_entry">
			<div class="resume_position">
				<h4><i><%= resume_entry.position %></i>
					<% if user_signed_in? %>
						<%= link_to 'Edit', edit_resume_entry_path(resume_entry), { class: "btn btn-default btn-xs edit_entry_btn" } %>
					<% end %>
				</h4>
				<% diff = resume_entry.date_difference %>
				<span class="w100fl">
					<% if resume_entry.company_url.nil? or resume_entry.company_url.blank? %>
						<%= resume_entry.company %>
					<% else %>
						<a href="<%= resume_entry.company_url %>" target="_blank"><%= resume_entry.company %></a>
					<% end %>
				</span>
				<span class="w100fl">
					<% enddate = resume_entry.is_current? ? "Present" : resume_entry.end_date.strftime("%b, %Y") %>
					<%= resume_entry.start_date.strftime("%b, %Y") %> - <%= enddate %>
					<i>(<%= "#{diff[0]} years, #{diff[1]} months" %>)</i>
				</span>
				<p><%= resume_entry.description.html_safe %></p>
			</div>
		</div>
	<% end %>

<% end %>

app/views/resumes/new.html.erb
<% content_for :main do %>
	<h3>New Resume</h3>
	<%= render 'form' %>
<% end %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Summary:</strong>
  <%= @resume.summary %>
</p>

<p>
  <strong>Education:</strong>
  <%= @resume.education %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @resume.skills %>
</p>

<p>
  <strong>Additional Information:</strong>
  <%= @resume.additional_info %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>